GET http://localhost:3000/messages

###

GET http://localhost:3000/messages/650b15f6dbba70bc9c6e07fd

###

POST http://localhost:3000/messages
Content-Type: application/json

{
    "author": "hej",
    "message": "Snatta på alsdkjfösla",
    "timestamp": "12:13:14",
    "read": false
}

###

PATCH http://localhost:3000/messages/650b15f6dbba70bc9c6e07fd

###

POST http://localhost:3000/asdfasdf

###

POST http://localhost:3000/messages/650add7180d1366c61657172
